### ISSUE TITLE
Problema com o campo VALOR / Float

### ISSUE THREAD

**Issue by duard** [eduardokum/laravel-boleto#256]
Semana passada consegui gerar alguns boletos de teste tranquilamente, porém, esta semana, quando seto o campo VALOR, os seguintes problemas são reportados

```

 $boleto = new Eduardokum\LaravelBoleto\Boleto\Banco\Bancoob(
        [
            'logo'                   => '756.png',
            'dataVencimento'         => $vencimento, //new \Carbon\Carbon(parse($dataVencimento)),
            'valor'               => 100.00,
            'multa'                  => false,
            'juros'                  => false,
            'numero'                 => $result->numero,
            'numeroDocumento'        => $result->numeroDocumento,
            'pagador'                => $result->pagador,
            'beneficiario'           => $result->beneficiario,
            'carteira'               => $result->carteira,
            'agencia'                => $result->agencia,
            'convenio'               => $result->convenio,
            'conta'                  => $result->conta,
            'descricaoDemonstrativo' => ['demonstrativo 1', 'demonstrativo 2', 'demonstrativo 3'],
            'instrucoes'             => ['instrucao 1', 'instrucao 2', 'instrucao 3'],
            // 'aceite'                 => 'S',
            // 'especieDoc'             => $result->especieDoc

            // 'logo'                   => '756.png',
            // 'dataVencimento'         => new \Carbon\Carbon(),
            // 'valor'                  => 5.58,
            // 'multa'                  => true,
            // 'juros'                  => false,
            // 'numero'                 => 1,
            // 'numeroDocumento'        => 1,
            'pagador'                => $pagador,
            'beneficiario'           => $beneficiario,
            // 'carteira'               => 1,
            // 'agencia'                => 1111,
            'convenio'               => 123123,
            // 'conta'                  => 22222,
            'aceite'                 => 'S',
            'especieDoc'             => 'DM',
        ]
    );
#0 C:\xampp\htdocs\dominio2.com.br\vendor\eduardokum\laravel-boleto\src\Boleto\AbstractBoleto.php(999): Eduardokum\LaravelBoleto\Util::nFloat(100, 2, false)
#1 C:\xampp\htdocs\dominio2.com.br\vendor\eduardokum\laravel-boleto\src\Util.php(911): Eduardokum\LaravelBoleto\Boleto\AbstractBoleto-&gt;setValor(100)
#2 C:\xampp\htdocs\dominio2.com.br\vendor\eduardokum\laravel-boleto\src\Boleto\AbstractBoleto.php(292): Eduardokum\LaravelBoleto\Util::fillClass(Object(Eduardokum\LaravelBoleto\Boleto\Banco\Bancoob), Array)
#3 C:\xampp\htdocs\dominio2.com.br\vendor\eduardokum\laravel-boleto\src\Boleto\Banco\Bancoob.php(13): Eduardokum\LaravelBoleto\Boleto\AbstractBoleto-&gt;__construct(Array)
#4 C:\xampp\htdocs\dominio2.com.br\src\routes.php(155): Eduardokum\LaravelBoleto\Boleto\Banco\Bancoob-&gt;__construct(Array)
#5 [internal function]: Closure-&gt;{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 C:\xampp\htdocs\dominio2.com.br\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 C:\xampp\htdocs\dominio2.com.br\vendor\slim\slim\Slim\Route.php(335): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#8 C:\xampp\htdocs\dominio2.com.br\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 C:\xampp\htdocs\dominio2.com.br\vendor\slim\slim\Slim\Route.php(313): Slim\Route-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 C:\xampp\htdocs\dominio2.com.br\vendor\slim\slim\Slim\App.php(495): Slim\Route-&gt;run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 C:\xampp\htdocs\dominio2.com.br\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 C:\xampp\htdocs\dominio2.com.br\vendor\slim\slim\Slim\App.php(388): Slim\App-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 C:\xampp\htdocs\dominio2.com.br\vendor\slim\slim\Slim\App.php(296): Slim\App-&gt;process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 C:\xampp\htdocs\dominio2.com.br\public\index.php(30): Slim\App-&gt;run()
#15 {main}
```

**Comment by duard** [comment]
O erro era que eu havia liberado a intl no php.ini mas não havia restartado o servidor.
