### ISSUE TITLE
Problemas BOLETO BRADESCO

### ISSUE THREAD

**Issue by duard** [eduardokum/laravel-boleto#278]
Pessoal, fiz o boleto SICOOB e tudo funcionou tranquilamente, porém, ao tentar fazer com o boleto BRADESCO, recebo os seguinte erro

```
<html>
    <head>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
        <title>Slim Application Error</title>
        <style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style>
    </head>
    <body>
        <h1>Slim Application Error</h1>
        <p>The application could not run because of the following error:</p>
        <h2>Details</h2>
        <div>
            <strong>Type:</strong> Error
        </div>
        <div>
            <strong>Message:</strong> Class 'Eduardokum\LaravelBoleto\Boleto\Banco\bradesco' not found
        </div>
        <div>
            <strong>File:</strong> /home/sigpharma/domains/apifin.sigpharma.net/public_html/src/routes.php
        </div>
        <div>
            <strong>Line:</strong> 300
        </div>
        <h2>Trace</h2>
        <pre>#0 [internal function]: Closure-&gt;{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /home/sigpharma/domains/apifin.sigpharma.net/public_html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /home/sigpharma/domains/apifin.sigpharma.net/public_html/vendor/slim/slim/Slim/Route.php(335): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /home/sigpharma/domains/apifin.sigpharma.net/public_html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /home/sigpharma/domains/apifin.sigpharma.net/public_html/vendor/slim/slim/Slim/Route.php(313): Slim\Route-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /home/sigpharma/domains/apifin.sigpharma.net/public_html/vendor/slim/slim/Slim/App.php(495): Slim\Route-&gt;run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /home/sigpharma/domains/apifin.sigpharma.net/public_html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /home/sigpharma/domains/apifin.sigpharma.net/public_html/vendor/slim/slim/Slim/App.php(388): Slim\App-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /home/sigpharma/domains/apifin.sigpharma.net/public_html/vendor/slim/slim/Slim/App.php(296): Slim\App-&gt;process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /home/sigpharma/domains/apifin.sigpharma.net/public_html/public/index.php(30): Slim\App-&gt;run()
#10 {main}</pre>
    </body>
</html>
```

**Comment by eduardokum** [comment]
O problema é 

`Eduardokum\LaravelBoleto\Boleto\Banco\bradesco`

O Bradesco minúsculo

Use

`Eduardokum\LaravelBoleto\Boleto\Banco\Bradesco`

**Comment by duard** [comment]
Estranho que funciona em localhost e não funciona no servidor, vou testar novamente e te retorno.

**Comment by duard** [comment]
Troquei lá na versão online e realmente funcionou, estranho, em localhost funciona com ambos, Bradesco e bradesco.
